#!/bin/bash
set -e

function check_we_are_in_vagrant {
  case `uname` in
      Linux)
          if [[ ! -d /vagrant ]] ; then
              echo "You need to be running in the vagrant VM to do this"
              exit 1
          fi
      ;;

      *)

          echo
          echo
          echo "You need to be running in your vagrant virtual machine to run this."
          echo
          echo "Run vagrant ssh from the root directory of the development environment and then re-run this script"
          echo
          exit 1
      ;;
  esac
}
